return {
  ["famiu/bufdelete.nvim"] = { disable = true },
  ["max397574/better-escape.nvim"] = { disable = true },
  ["dhruvasagar/vim-table-mode"] = require "user.plugins.vim-table-mode",
  ["echasnovski/mini.nvim"] = require "user.plugins.mini",
  ["ethanholz/nvim-lastplace"] = require "user.plugins.nvim-lastplace",
  ["folke/zen-mode.nvim"] = require "user.plugins.zen-mode",
  ["hrsh7th/cmp-calc"] = require "user.plugins.cmp-calc",
  ["hrsh7th/cmp-emoji"] = require "user.plugins.cmp-emoji",
  ["jbyuki/nabla.nvim"] = require "user.plugins.nabla",
  ["jc-doyle/cmp-pandoc-references"] = require "user.plugins.cmp-pandoc-references",
  ["kdheepak/cmp-latex-symbols"] = require "user.plugins.cmp-latex-symbols",
  ["lukas-reineke/headlines.nvim"] = require "user.plugins.headlines",
  ["mfussenegger/nvim-dap"] = require "user.plugins.dap",
  ["mickael-menu/zk-nvim"] = require "user.plugins.zk",
  ["mtikekar/nvim-send-to-term"] = require "user.plugins.nvim-send-to-term",
  ["nvim-telescope/telescope-bibtex.nvim"] = require "user.plugins.telescope-bibtex",
  ["nvim-telescope/telescope-file-browser.nvim"] = require "user.plugins.telescope-file-browser",
  ["nvim-telescope/telescope-hop.nvim"] = require "user.plugins.telescope-hop",
  ["nvim-telescope/telescope-media-files.nvim"] = require "user.plugins.telescope-media-files",
  ["nvim-telescope/telescope-project.nvim"] = require "user.plugins.telescope-project",
  ["nvim-treesitter/nvim-treesitter-textobjects"] = require "user.plugins.nvim-treesitter-textobjects",
  ["phaazon/hop.nvim"] = require "user.plugins.hop",
  ["rcarriga/nvim-dap-ui"] = require "user.plugins.dapui",
  ["vitalk/vim-simple-todo"] = require "user.plugins.vim-simple-todo",
  ["wakatime/vim-wakatime"] = require "user.plugins.vim-wakatime",
  ["ziontee113/syntax-tree-surfer"] = require "user.plugins.syntax-tree-surfer",
  ["akinsho/git-conflict.nvim"] = require "user.plugins.git-conflict",
  "davidgranstrom/nvim-markdown-preview",
  "ellisonleao/gruvbox.nvim",
  ["vimwiki/vimwiki"] = require "user.plugins.vimwiki.init",
}
